services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  loki:
    image: grafana/loki:latest
    ports:
      - '3100:3100'

  alloy: # replaces promtail
    image: grafana/alloy:latest
    volumes:
      - /var/log/app:/var/log/app # same mount as before
      - ./monitoring/alloy/config.alloy:/etc/alloy/config.alloy
    command:
      - run
      - /etc/alloy/config.alloy
    ports:
      - '12345:12345' # Alloy UI

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
